#ifndef SHM_ERROR_H
#define SHM_ERROR_H

enum {
  E_SHM_SYSTEM = -1,
  E_SHM_OK,
  E_SHM_CREAT_SEGINFO_FAILED,
  E_SHM_EMPTY,
  E_SHM_SAME_KEY_EXIST,
  E_SHM_DATA_CORRUPTED,
  E_SHM_TREE_NEW_FAILED,
  E_SHM_PTR_INVALID,
  E_SHM_KEY_NOT_FOUND,
  E_SHM_VAL_UPDATE_EXCEED_MAX_SIZE,
  E_SHM_VAL_SIZE_INVALID,
  E_SHM_KEY_ZERO_LENGTH,
  E_SHM_INIT_ONLY_ONCE,
  E_SHM_INVALID_PARAMS,
};

#endif /* SHM_ERROR_H */

